version: '3'

services:
  # Django Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust port if necessary
    volumes:
      - .:/app  # Mount your Django project directory
    depends_on:
      - db
    networks:
      - webnet
    env_file:
      - .env  # Update with the path to your .env file

  # PostgreSQL Service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet
    env_file:
      - .env  # Update with the path to your .env file

  # TimescaleDB Extension
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TSDB_TELEMETRY_DB: ${TSDB_TELEMETRY_DB}
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    networks:
      - webnet
    env_file:
      - .env  # Update with the path to your .env file

volumes:
  postgres_data:  # Volume for PostgreSQL data persistence

networks:
  webnet:
