# Generated by Django 4.2.7 on 2023-12-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry_data',
            },
        ),
    ]
